version: '2'
services:
    back:
        image: ekino/docker-buildbox:golang1.7-2017.02.07
        command: modd
        ports:
            - "127.0.0.1:8000:8000"
        volumes:
            - ".:/go/src/github.com/rande/gonode:cached"
            - "gopath:/go"
        working_dir: /go/src/github.com/rande/gonode
        links:
            - influxdb
            - database
        environment:
            POSTGRES_PASSWORD: gonode
            POSTGRES_DB: gonode
            INFLUXDB_HOST: influxdb
            PATH: /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#    front:
#        image: ekino/docker-buildbox:node7.5-2017.02.07
#        command: ./node_modules/.bin/webpack-dev-server --config webpack-dev-server.config.js --inline --colors
#        ports:
#            - "127.0.0.1:3000:3000"
#        volumes:
#            - "./admin:/code/admin"
#        working_dir: /code/admin
#        links:
#            - back

    influxdb:
        image: influxdb
        volumes:
            - "./data/influxdb:/var/lib/influxdb/data"
    database:
        image: postgres:9.5
        volumes:
            - "./data/postgresql:/var/lib/postgresql/data"
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_PASSWORD: gonode
            POSTGRES_DB: gonode

volumes:
  gopath: